"""
Controlled Academic Explanation Engine - Microsoft Phi-2
Generates explanations only, never new facts. Fully grounded, deterministic.

Architecture:
1. Load Phi-2 once at startup (4-bit quantized)
2. Only accepts structured grounded input
3. System guard enforces grounding
4. Deterministic decoding (temp=0.2, no sampling)
5. Hallucination guard validates output
6. Domain restriction enforced by MetaController
7. No chat/open-ended generation
8. Academic domain only

Safety Contract:
- Input: structured with grounded_data
- Output: explanation only
- Validation: post-generation hallucination check
- Refusal: if grounded_data empty or validation fails
"""

from typing import Dict, Any, Optional, List, Tuple
import logging
from datetime import datetime
import re
import warnings

try:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    from transformers import TextIteratorStreamer
    HAS_TRANSFORMERS = True
except ImportError:
    HAS_TRANSFORMERS = False

import numpy as np

logger = logging.getLogger(__name__)


class ControlledExplanationValidator:
    """
    Hallucination Guard Layer (Critical)
    Validates generated explanations against grounded data.
    """
    
    def __init__(self):
        """Initialize validator."""
        self.validation_history = []
        self.failed_validations = 0
        self.passed_validations = 0
    
    def validate(
        self,
        generated_text: str,
        grounded_data: Dict[str, Any]
    ) -> Tuple[bool, str]:
        """
        Validate generated explanation against grounded data.
        
        Args:
            generated_text: Text generated by model
            grounded_data: Dictionary with factual_result, numeric_result, code_snippet
            
        Returns:
            Tuple of (is_valid, reason)
        """
        validation_checks = []
        
        # Check 1: Extract numbers from output
        output_numbers = self._extract_numbers(generated_text)
        numeric_result = grounded_data.get("numeric_result")
        
        if numeric_result is not None:
            # Convert numeric result to string for comparison
            expected_numbers = self._extract_numbers(str(numeric_result))
            
            # Allow explanation to reference the number
            if output_numbers and expected_numbers:
                # Check if any output number matches expected
                numbers_match = any(
                    abs(float(on) - float(en)) < 0.01
                    for on in output_numbers if on.replace('.', '', 1).isdigit()
                    for en in expected_numbers if en.replace('.', '', 1).isdigit()
                )
                
                if not numbers_match:
                    validation_checks.append({
                        "check": "numeric_match",
                        "pass": False,
                        "reason": f"Output numbers {output_numbers} don't match expected {expected_numbers}"
                    })
                else:
                    validation_checks.append({
                        "check": "numeric_match",
                        "pass": True
                    })
            elif output_numbers and not expected_numbers:
                # Generated numbers that shouldn't exist
                validation_checks.append({
                    "check": "numeric_hallucination",
                    "pass": False,
                    "reason": f"Generated unexpected numbers: {output_numbers}"
                })
        
        # Check 2: Extract named entities (simple)
        output_entities = self._extract_entities(generated_text)
        grounded_entities = self._extract_grounded_entities(grounded_data)
        
        # Entities must be in grounded data or be explanation words
        explanation_words = {
            "algorithm", "function", "variable", "parameter", "return",
            "loop", "condition", "array", "string", "binary", "search",
            "explanation", "example", "because", "therefore", "thus",
            "calculates", "demonstrates", "shows", "illustrates"
        }
        
        new_entities = [
            e for e in output_entities
            if e not in grounded_entities and e.lower() not in explanation_words
        ]
        
        if new_entities:
            validation_checks.append({
                "check": "entity_hallucination",
                "pass": False,
                "reason": f"Introduced new entities not in grounded data: {new_entities}"
            })
        else:
            validation_checks.append({
                "check": "entity_hallucination",
                "pass": True
            })
        
        # Check 3: Factual result not modified
        factual_result = grounded_data.get("factual_result")
        if factual_result:
            if factual_result.lower() not in generated_text.lower():
                # Allow summarization, but not contradiction
                if self._is_contradictory(generated_text, factual_result):
                    validation_checks.append({
                        "check": "factual_modification",
                        "pass": False,
                        "reason": "Factual result was contradicted or significantly modified"
                    })
                else:
                    validation_checks.append({
                        "check": "factual_modification",
                        "pass": True,
                        "reason": "Factual result summarized appropriately"
                    })
            else:
                validation_checks.append({
                    "check": "factual_modification",
                    "pass": True
                })
        
        # Check 4: Output length reasonable
        if len(generated_text) < 20:
            validation_checks.append({
                "check": "minimum_content",
                "pass": False,
                "reason": "Generated text too short to be meaningful explanation"
            })
        elif len(generated_text) > 2000:
            validation_checks.append({
                "check": "maximum_length",
                "pass": False,
                "reason": "Generated text too long (>2000 chars)"
            })
        else:
            validation_checks.append({
                "check": "length",
                "pass": True
            })
        
        # Overall validation
        all_pass = all(check["pass"] for check in validation_checks)
        
        # Log result
        if all_pass:
            self.passed_validations += 1
            reason = "All validation checks passed"
        else:
            self.failed_validations += 1
            failed = [c for c in validation_checks if not c["pass"]]
            reason = "; ".join(f"{f['check']}: {f.get('reason', 'failed')}" for f in failed)
        
        self.validation_history.append({
            "timestamp": datetime.now().isoformat(),
            "valid": all_pass,
            "checks": validation_checks,
            "reason": reason
        })
        
        return all_pass, reason
    
    @staticmethod
    def _extract_numbers(text: str) -> List[str]:
        """Extract all numbers from text."""
        return re.findall(r'\b\d+\.?\d*\b', text)
    
    @staticmethod
    def _extract_entities(text: str) -> set:
        """Extract capitalized words (simple entity extraction)."""
        return set(word for word in text.split() if word[0].isupper() and len(word) > 2)
    
    @staticmethod
    def _extract_grounded_entities(grounded_data: Dict[str, Any]) -> set:
        """Extract entities from grounded data."""
        entities = set()
        
        for key, value in grounded_data.items():
            if isinstance(value, str):
                entities.update(word for word in value.split() if word[0].isupper() and len(word) > 2)
            elif isinstance(value, dict):
                for v in value.values():
                    if isinstance(v, str):
                        entities.update(word for word in v.split() if word[0].isupper() and len(word) > 2)
        
        return entities
    
    @staticmethod
    def _is_contradictory(generated_text: str, factual_result: str) -> bool:
        """Check if generated text contradicts factual result."""
        contradiction_words = {"not", "no", "cannot", "wrong", "false", "incorrect", "failed"}
        
        fact_words = set(factual_result.lower().split())
        gen_words = set(generated_text.lower().split())
        
        # If contradicted, would have opposite meaning
        # Simple check: if factual said "true" and gen says "false"
        if "true" in fact_words and "false" in gen_words:
            return True
        if "false" in fact_words and "true" in gen_words:
            return True
        
        return False
    
    def get_stats(self) -> Dict[str, Any]:
        """Get validation statistics."""
        return {
            "total_validations": len(self.validation_history),
            "passed": self.passed_validations,
            "failed": self.failed_validations,
            "pass_rate": (
                self.passed_validations / len(self.validation_history)
                if self.validation_history else 0
            ),
            "recent_failures": [
                h for h in self.validation_history[-5:]
                if not h["valid"]
            ]
        }


class Phi2ExplanationEngine:
    """
    Production-Grade Controlled Explanation Engine using Microsoft Phi-2.
    
    Generates academic explanations only, never new facts.
    Fully grounded, deterministic, locally-run, safe.
    """
    
    # Safe decoding parameters (deterministic, limited)
    SAFE_GENERATION_CONFIG = {
        "temperature": 0.2,          # Low randomness
        "top_p": 0.9,                # Classic nucleus sampling, conservative
        "do_sample": False,          # Deterministic
        "max_new_tokens": 300,       # Limit length
        "early_stopping": True,      # Stop at <|end|> if present
        "repetition_penalty": 1.0,   # Don't penalize unique tokens
    }
    
    # System guard (mandatory)
    SYSTEM_GUARD = """You are a controlled academic explanation engine.

Rules (strict):
- You must ONLY explain the provided grounded data.
- You must NOT introduce new facts.
- You must NOT guess missing information.
- You must NOT modify numeric results.
- You must NOT hallucinate.
- If information is missing, say so clearly.
- Do not answer outside academic domain.

Be concise and clear."""
    
    def __init__(self, use_quantization: bool = True, device: str = "auto"):
        """
        Initialize Phi-2 explanation engine.
        
        Args:
            use_quantization: Use 4-bit quantization (recommended)
            device: "auto", "cuda", "cpu"
        """
        self.model_name = "microsoft/phi-2"
        self.use_quantization = use_quantization
        self.device = device
        
        self.model = None
        self.tokenizer = None
        self.validator = ControlledExplanationValidator()
        
        self.inference_count = 0
        self.failed_generations = 0
        self.successful_explanations = 0
        self.inference_times = []
        
        self.is_loaded = False
        
        logger.info("Phi2ExplanationEngine initialized (model not loaded yet)")
    
    def load(self) -> bool:
        """
        Load Phi-2 model once at startup.
        Uses 4-bit quantization by default.
        
        Returns:
            True if loaded successfully
        """
        if self.is_loaded:
            logger.info("Model already loaded")
            return True
        
        if not HAS_TRANSFORMERS:
            logger.error("Transformers library not available")
            return False
        
        try:
            logger.info(f"Loading {self.model_name}...")
            
            # Quantization config (4-bit recommended)
            if self.use_quantization:
                logger.info("Loading with 4-bit quantization (bitsandbytes)")
                quantization_config = BitsAndBytesConfig(
                    load_in_4bit=True,
                    bnb_4bit_compute_dtype=torch.float16,
                    bnb_4bit_use_double_quant=True,
                    bnb_4bit_quant_type="nf4"
                )
            else:
                quantization_config = None
            
            # Load model
            self.model = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                torch_dtype=torch.float16,
                device_map=self.device,
                quantization_config=quantization_config if self.use_quantization else None,
                trust_remote_code=True,
                attn_implementation="eager"  # For compatibility
            )
            
            # Load tokenizer
            self.tokenizer = AutoTokenizer.from_pretrained(
                self.model_name,
                trust_remote_code=True
            )
            
            self.is_loaded = True
            logger.info(f"✓ Phi-2 model loaded successfully")
            logger.info(f"  Model dtype: {self.model.dtype}")
            logger.info(f"  Device map: {self.device}")
            logger.info(f"  Quantization: {self.use_quantization}")
            
            return True
            
        except Exception as e:
            logger.error(f"Failed to load Phi-2: {e}")
            self.is_loaded = False
            return False
    
    def execute(
        self,
        query: str,
        grounded_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate explanation with grounded data.
        
        Args:
            query: Original user query
            grounded_data: Dict with factual_result, numeric_result, code_snippet
            
        Returns:
            Dictionary with status, explanation, confidence, metadata
        """
        start_time = datetime.now()
        self.inference_count += 1
        
        # Step 1: Validate input (Critical)
        if not self._validate_grounded_input(query, grounded_data):
            return self._response_refusal(
                "Insufficient grounded data for explanation",
                start_time
            )
        
        # Step 2: Build safe prompt with system guard
        safe_prompt = self._build_safe_prompt(query, grounded_data)
        
        # Step 3: Generate with deterministic decoding
        generated_text = self._generate_safe(safe_prompt)
        
        if generated_text is None:
            self.failed_generations += 1
            return self._response_refusal("Generation failed", start_time)
        
        # Step 4: Hallucination validation (Critical)
        is_valid, validation_reason = self.validator.validate(generated_text, grounded_data)
        
        if not is_valid:
            self.failed_generations += 1
            logger.warning(f"Explanation failed validation: {validation_reason}")
            return self._response_refusal(
                f"Explanation failed safety validation: {validation_reason}",
                start_time
            )
        
        # Step 5: Success
        self.successful_explanations += 1
        processing_time = (datetime.now() - start_time).total_seconds() * 1000
        self.inference_times.append(processing_time)
        
        return {
            "status": "success",
            "explanation": generated_text.strip(),
            "confidence": 0.9,  # High confidence after validation
            "grounded": True,
            "metadata": {
                "model": self.model_name,
                "decoding": "deterministic",
                "grounded_keys": list(grounded_data.keys()),
                "validation_passed": is_valid,
                "processing_time_ms": round(processing_time, 2)
            },
            "engine": "transformer",
            "model_version": "phi-2"
        }
    
    def _validate_grounded_input(self, query: str, grounded_data: Dict[str, Any]) -> bool:
        """
        Validate that grounded_data is provided and non-empty.
        """
        if not grounded_data:
            logger.warning("Grounded data is empty")
            return False
        
        # At least one grounding source must be present
        has_grounding = any(
            grounded_data.get(key) is not None
            for key in ["factual_result", "numeric_result", "code_snippet"]
        )
        
        if not has_grounding:
            logger.warning("No grounding sources provided")
            return False
        
        return True
    
    def _build_safe_prompt(self, query: str, grounded_data: Dict[str, Any]) -> str:
        """
        Build safe prompt with system guard.
        """
        # Format grounding data
        grounded_str = ""
        
        if grounded_data.get("factual_result"):
            grounded_str += f"Fact: {grounded_data['factual_result']}\n"
        
        if grounded_data.get("numeric_result"):
            grounded_str += f"Numeric Result: {grounded_data['numeric_result']}\n"
        
        if grounded_data.get("code_snippet"):
            grounded_str += f"Code:\n{grounded_data['code_snippet']}\n"
        
        # Build prompt
        prompt = f"""{self.SYSTEM_GUARD}

Grounded Data:
{grounded_str}

User Question:
{query}

Explanation:"""
        
        return prompt
    
    def _generate_safe(self, prompt: str) -> Optional[str]:
        """
        Generate explanation with safe parameters.
        Deterministic, no sampling, limited length.
        """
        if not self.is_loaded or self.model is None:
            logger.error("Model not loaded")
            return None
        
        try:
            # Tokenize
            inputs = self.tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)
            inputs = {k: v.to(self.model.device) for k, v in inputs.items()}
            
            # Generate with safe parameters
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    **self.SAFE_GENERATION_CONFIG,
                    pad_token_id=self.tokenizer.eos_token_id
                )
            
            # Decode
            generated_text = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
            
            # Extract just the explanation part (after "Explanation:")
            if "Explanation:" in generated_text:
                explanation = generated_text.split("Explanation:")[-1].strip()
            else:
                explanation = generated_text
            
            return explanation
            
        except Exception as e:
            logger.error(f"Generation error: {e}")
            return None
    
    def _response_refusal(self, reason: str, start_time: datetime) -> Dict[str, Any]:
        """Create refusal response."""
        return {
            "status": "refusal",
            "explanation": None,
            "reasoning": reason,
            "confidence": 0.0,
            "grounded": False,
            "processing_time_ms": round((datetime.now() - start_time).total_seconds() * 1000, 2),
            "engine": "transformer",
            "model_version": "phi-2"
        }
    
    def get_stats(self) -> Dict[str, Any]:
        """Get engine statistics."""
        avg_inference_time = (
            sum(self.inference_times) / len(self.inference_times)
            if self.inference_times else 0
        )
        
        return {
            "is_loaded": self.is_loaded,
            "model_name": self.model_name,
            "total_inferences": self.inference_count,
            "successful_explanations": self.successful_explanations,
            "failed_generations": self.failed_generations,
            "success_rate": (
                self.successful_explanations / self.inference_count
                if self.inference_count > 0 else 0
            ),
            "average_inference_time_ms": round(avg_inference_time, 2),
            "max_inference_time_ms": round(max(self.inference_times), 2) if self.inference_times else 0,
            "validator_stats": self.validator.get_stats(),
            "generation_config": self.SAFE_GENERATION_CONFIG
        }


if __name__ == "__main__":
    # Quick test
    import logging
    logging.basicConfig(level=logging.INFO)
    
    print("=" * 70)
    print("Phi-2 Controlled Explanation Engine - Test")
    print("=" * 70)
    
    engine = Phi2ExplanationEngine(use_quantization=True)
    
    # Load model
    if not engine.load():
        print("✗ Failed to load model")
        exit(1)
    
    print("✓ Model loaded successfully")
    
    # Test explanation
    test_grounded = {
        "numeric_result": 100,
        "factual_result": "20% of 500 equals 100",
        "code_snippet": None
    }
    
    result = engine.execute("Why does 20% of 500 equal 100?", test_grounded)
    
    print(f"\nResult Status: {result['status']}")
    if result['status'] == 'success':
        print(f"Explanation:\n{result['explanation']}")
        print(f"Confidence: {result['confidence']}")
    else:
        print(f"Refusal: {result.get('reasoning', 'Unknown')}")
    
    print(f"\nStats: {engine.get_stats()}")
