"""
Transformer Engine - Explanation Only
Uses google/flan-t5-small for conceptual explanations.
NO FACTS. NO NUMBERS. NO LEADERS. EXPLANATION ONLY.
"""
from typing import Dict, Any
import warnings

# Suppress warnings
warnings.filterwarnings('ignore')

try:
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
    TRANSFORMERS_AVAILABLE = True
except ImportError:
    TRANSFORMERS_AVAILABLE = False
    print("⚠ transformers library not installed. Install with: pip install transformers torch")


class TransformerEngine:
    """
    Uses transformer ONLY for conceptual explanations.
    Strictly forbidden from answering facts or numbers.
    """
    
    def __init__(self, model_name: str = "google/flan-t5-small"):
        """
        Initialize transformer engine.
        
        Args:
            model_name: HuggingFace model name
        """
        self.model_name = model_name
        self.model = None
        self.tokenizer = None
        self.is_loaded = False
        
        if TRANSFORMERS_AVAILABLE:
            self._load_model()
        else:
            print("⚠ Transformer engine disabled - transformers library not available")
    
    def _load_model(self):
        """Load the transformer model and tokenizer."""
        try:
            print(f"Loading {self.model_name}...")
            self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self.model = AutoModelForSeq2SeqLM.from_pretrained(self.model_name)
            self.is_loaded = True
            print(f"✓ Transformer engine ready ({self.model_name})")
        except Exception as e:
            print(f"✗ Failed to load transformer model: {e}")
            self.is_loaded = False
    
    def execute(self, query: str, features: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate explanation using transformer.
        
        Args:
            query: User query
            features: Features from input analyzer
            
        Returns:
            Dictionary with answer, confidence, strategy
        """
        # Safety check - ensure this is an explanation query
        query_lower = features.get("lowercase_text", query.lower())
        
        # Block if query asks for facts
        fact_indicators = ['who is', 'what is the capital', 'when was', 'where is', 
                          'population of', 'president of', 'leader of', 'name of']
        if any(indicator in query_lower for indicator in fact_indicators):
            return {
                "answer": "This appears to be a factual query. Transformer engine only handles conceptual explanations. Query should be routed to Retrieval engine.",
                "confidence": 0.0,
                "strategy": "TRANSFORMER",
                "reason": "Blocked - factual query sent to transformer engine (routing error)"
            }
        
        # Block if query contains numbers
        if features.get("has_digits", False) and features.get("has_math_operators", False):
            return {
                "answer": "This appears to be a numerical query. Transformer engine only handles conceptual explanations. Query should be routed to ML engine.",
                "confidence": 0.0,
                "strategy": "TRANSFORMER",
                "reason": "Blocked - numerical query sent to transformer engine (routing error)"
            }
        
        # Generate explanation
        if not self.is_loaded:
            return self._fallback_explanation(query)
        
        try:
            explanation = self._generate_explanation(query)
            return {
                "answer": explanation,
                "confidence": 0.7,  # Lower confidence for generated content
                "strategy": "TRANSFORMER",
                "reason": "Conceptual explanation generated by transformer model"
            }
        except Exception as e:
            print(f"✗ Transformer generation error: {e}")
            return self._fallback_explanation(query)
    
    def _generate_explanation(self, query: str) -> str:
        """
        Generate explanation using the transformer model.
        
        Args:
            query: Query string
            
        Returns:
            Generated explanation
        """
        # Prepare prompt for explanation
        prompt = f"Explain this concept: {query}"
        
        # Tokenize
        inputs = self.tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)
        
        # Generate
        outputs = self.model.generate(
            **inputs,
            max_length=150,
            min_length=30,
            num_beams=4,
            temperature=0.7,
            do_sample=False,
            early_stopping=True
        )
        
        # Decode
        explanation = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        return explanation
    
    def _fallback_explanation(self, query: str) -> Dict[str, Any]:
        """
        Fallback explanation when model is not available.
        
        Args:
            query: Query string
            
        Returns:
            Fallback response
        """
        return {
            "answer": (
                "I can provide conceptual explanations, but the transformer model is not currently loaded. "
                "Please ensure the required packages are installed: pip install transformers torch"
            ),
            "confidence": 0.0,
            "strategy": "TRANSFORMER",
            "reason": "Transformer model not available - fallback response"
        }
    
    def validate_explanation_query(self, query: str) -> bool:
        """
        Validate that query is appropriate for explanation.
        
        Args:
            query: Query string
            
        Returns:
            True if valid for explanation, False otherwise
        """
        query_lower = query.lower()
        
        # Must contain explanation keywords
        explanation_keywords = ['why', 'how', 'explain', 'describe', 'what does', 'what are']
        has_explanation_keyword = any(kw in query_lower for kw in explanation_keywords)
        
        # Must NOT be asking for specific facts
        fact_keywords = ['who is', 'when was', 'where is', 'capital of', 'president', 'population']
        has_fact_keyword = any(kw in query_lower for kw in fact_keywords)
        
        # Must NOT be asking for numbers
        has_numbers = any(char.isdigit() for char in query)
        math_operators = ['+', '-', '*', '/', 'calculate', 'compute']
        has_math = any(op in query_lower for op in math_operators)
        
        return has_explanation_keyword and not has_fact_keyword and not (has_numbers and has_math)
    
    def get_stats(self) -> Dict[str, Any]:
        """
        Get statistics about transformer usage.
        
        Returns:
            Dictionary with statistics
        """
        return {
            "model_name": self.model_name,
            "is_loaded": self.is_loaded,
            "transformers_available": TRANSFORMERS_AVAILABLE
        }
